### ISSUE TITLE
Add a license file if this is an open-source project

### ISSUE THREAD

**Issue by ajturner** [geometalab/ArcGISConnector-QGIS-Plugin#1]
Currently the only "license" is `(C) 2011-2014 GeoApt LLC - geoapt.com` 

if this is intended to be open and reusable, please clarify and add a LICENSE file.

**Comment by ajturner** [comment]
I see GPL license in the files, but good to also add to the readme and explicit file.

**Comment by sfkeller** [comment]
As said in mail notification: It will be GPL v2 (like all QGIS plugins). Also README.md will be added next days...
