### ISSUE TITLE
xml not recognised as a supported file format

### ISSUE THREAD

**Issue by aaschwanden** [geometalab/ArcGISConnector-QGIS-Plugin#11]
Hi,

I'm running QGIS 2.8-Wien on OS X installed via MacPorts.

After installing the ArcGIS REST API Connector, I'm able to connect to http://services.arcgisonline.com/arcgis/rest/services to see all available layers. Now, no matter which layer I try to import I get something like:

```
Cannot open GDAL dataset /Users/andy/.qgis2/python/plugins/connector/tmp/World_Dark_Gray_Base.xml:
`/Users/andy/.qgis2/python/plugins/connector/tmp/World_Dark_Gray_Base.xml' not recognised as a supported file format.
```

Do I need to configure GDAL with an additional plugin, or am I missing something?

Thanks,

Andy

**Comment by sfkeller** [comment]
Hi, You seem to try to load a raster based service which is not supported yet by this plugin - only vector (Feature Services). The plugin actually is still in alpha stage and will be updated possibly around end of August 2015. I updated the github README right now.
