### ISSUE TITLE
Does not appear to work with thousands of features

### ISSUE THREAD

**Issue by berniejconnors** [geometalab/ArcGISConnector-QGIS-Plugin#14]
Appears to work well with a service that has a relatively small number of features but I could not get it to work with feature services that have thousands of features.  I tried zooming in to a small area and only requesting features within the current extent but I had no luck.  

I manage an ArcGIS Server installation for the province of New Brunswick.  We have many map services that could be useful for testing.  Our ArcGIS Server REST services directory can be found here - http://geonb.snb.ca/ArcGIS/rest/services

I had success with the following map services:
Aboriginal Lands - http://geonb.snb.ca/ArcGIS/rest/services/GeoNB_Basemap_FirstNations/MapServer/0
Imagery Inventory - http://geonb.snb.ca/ArcGIS/rest/services/Imagery_Inventory/Imagery_Inventory/FeatureServer/1

I did not have success with these map services:
Property maps (~800,000 polygons, scale threshold 32,000) - http://geonb.snb.ca/ArcGIS/rest/services/Imagery_Inventory/Imagery_Inventory/FeatureServer/1
NB Road Network - http://geonb.snb.ca/ArcGIS/rest/services/GeoNB_Basemap_NBRN/MapServer/1

Get in touch if you have questions about our map services.

**Comment by sfkeller** [comment]
Hi Bernie,
Thanks for the report. I did some tests and got following results and remarks.

I could successfully load "Property maps". There are only 73 features as can be seen in the "ArcGIS Map" weblink in the weblink you gave.  => Can you check again?

"NBR road network" is a different thing: It seems to be huge (800'000 features):
- I see the first 1000 lines delivered by the server. Then transferring stops. 
- Your ArcGIS server has Version 10.05 and this is not supporting "maxrecordscount" (newer servers and our plugin support this.
- This ArcGIS REST API was not meant as download service and exchanging this amount of data without filtering will produce issues anyway. So the only intermediate solution is to zoom in.
- While zooming in, I got errors from the plugin which indicate that it has problems handling bbox with coordinate reference system which are different from the QGIS project. We'll investigate this.

**Comment by vr00n** [comment]
What about this - https://nycstreetstg.net/arcgis/rest/services/NYCStreets/StreetAssLastResurf/MapServer/0

It is only downloading 1000 features at a time. Anyway I can get it to download more than this ?

**Comment by faustos** [comment]
More than the number of features specified by the MacRecordCount parameter (which is set to 1000 at your layer) can only be retrieved if the server supports pagination. This feature is only available for ArcGIS server versions starting from 10.3. Unfortunately the nycstreetstg server still operates at 10.2. If you know the operator you could ask him to upgrade and enable pagination. Sorry I could not be of more help on this occasion.

**Comment by vr00n** [comment]
Thanks - that helps !
