### ISSUE TITLE
More details on how to install

### ISSUE THREAD

**Issue by ajturner** [geometalab/ArcGISConnector-QGIS-Plugin#2]
The details for building and installing on 2.x are lite. I installed PyQT and used pyuic4 on the two .ui files and pyrcc on the rsc file. However it doesn't show up in the plugins list. 

mac 10.9

**Comment by sfkeller** [comment]
The usual and most convenient way to install Python plugins on any supported platform (Linux, Windows, Mac) is simply by selecting them inside QGIS in menu "Extensions > Manage and install extensions". 
There are ways to install plugins directly but this is only recommended for devs.
At the time you have tested this plugin, it was not yet registered in the Plugin repository (http://plugins.qgis.org/plugins/connector/ ) - now it is!

**Comment by ajturner** [comment]
Thanks, I had specifically meant, "if developing locally, how to is ally through the QGIS extensions " 

That wasn't working at the time I registered this issue. Will it work now to do local build and istalls for development?

**Comment by sfkeller** [comment]
I think, it's only a matter of copying the plugin source into the local plugin directory of QGIS. See e.g. http://gis.stackexchange.com/questions/26979/how-to-install-a-qgis-plugin-when-offline .
